# Etapa 1: Compilación
FROM maven:3.8.5-openjdk-17 AS build

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app


COPY pom.xml .


RUN mvn dependency:go-offline

# Copia el código fuente al contenedor
COPY src ./src


RUN mvn clean package -DskipTests

# Etapa 2: Ejecución
FROM openjdk:17-jdk-alpine

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app


COPY --from=build /app/target/springboot-backend-elpisito-0.0.1-SNAPSHOT.jar /app/springboot-backend-elpisito.jar
COPY mediafiles /app/mediafiles


EXPOSE 8080


ENTRYPOINT ["java", "-jar", "/app/springboot-backend-elpisito.jar"]
